config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#main'

  resources :students
  resources :teachers do
    member do
      get 'students'
    end
  end

  # This adds the APIPie interface at /apipie
  apipie
end

app/models/teacher.rb
# This models teachers in our app.
#
# A Teacher teaches zero or more {#students}.
class Teacher < ApplicationRecord
  include Person

  # @!attribute [r] id
  #   @return [Integer] the teacher ID.  This uniquely identifies the teacher.

  # @!attribute students
  #   @return [<Student>] a collection of {Student}s presently taught by this
  #     teacher.
  has_many :students, dependent: :nullify, inverse_of: :teacher
end

app/controllers/teachers_controller.rb
# This handles CRUD operations for teachers
class TeachersController < ApplicationController
  before_action :set_teacher, only: %i[show edit update destroy students]

  # GET /teachers
  # GET /teachers.json
  def index
    @teachers = Teacher.all
  end

  # GET /teachers/1.json
  def show
    respond_to do |format|
      format.html { redirect_to Teacher }
      format.json { render :show }
    end
  end

  # GET /teachers/new
  def new
    @teacher = Teacher.new
  end

  # GET /teachers/1/edit
  def edit; end

  # POST /teachers
  # POST /teachers.json
  def create
    @teacher = Teacher.new(teacher_params)

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to Teacher, notice: 'Teacher was successfully created.' }
        format.json { render :show, status: :created, location: @teacher }
      else
        format.html { render :new }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teachers/1
  # PATCH/PUT /teachers/1.json
  def update
    respond_to do |format|
      if @teacher.update(teacher_params)
        format.html { redirect_to Teacher, notice: 'Teacher was successfully updated.' }
        format.json { render :show, status: :ok, location: @teacher }
      else
        format.html { render :edit }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1
  # DELETE /teachers/1.json
  def destroy
    @teacher.destroy
    respond_to do |format|
      format.html { redirect_to teachers_url, notice: 'Teacher was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /teachers/1/students
  def students
    @students = @teacher.students.order(:name).includes(lesson_part: :lesson).all
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_teacher
    @teacher = Teacher.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def teacher_params
    params.require(:teacher).permit(:name)
  end
end

app/helpers/teachers_helper.rb
# This is where helper methods for {TeachersController} would go, if there were
# any.
module TeachersHelper
end

app/views/teachers/_form.html.erb
<%= render 'person/form', person: teacher, name: 'teacher', back: teachers_path %>

app/views/teachers/edit.html.erb
<h1 class="title">Editing Teacher</h1>

<%= render 'form', teacher: @teacher %>

app/views/teachers/index.html.erb
<%= render 'application/notice', notice: notice %>

<h1 class="title">Teachers</h1>

<table class="table is-striped is-hoverable">
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @teachers.each do |teacher| %>
      <tr>
        <td><%= teacher.name %></td>
        <td>
          <div class="buttons has-addons">
            <%= link_to 'Students', students_teacher_path(teacher), class: 'button' %>
            <%= link_to 'Edit', edit_teacher_path(teacher), class: 'button' %>
            <%= link_to 'Destroy', teacher, method: :delete, data: { confirm: 'Are you sure?' }, class: 'button' %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Teacher', new_teacher_path, class: 'button is-link' %>

app/views/teachers/new.html.erb
<h1 class="title">New Teacher</h1>

<%= render 'form', teacher: @teacher %>

app/views/teachers/students.html.erb
<h1 class="title"><%= @teacher.name %>'s students</h1>

<% if @students.empty? %>
  <div class="notification is-warning">This teacher has no students</div>
<% else %>
  <table class="table is-striped is-hoverable">
    <thead>
      <tr>
        <th>Name</th>
        <th>Current Lesson</th>
      </tr>
    </thead>

    <tbody>
      <% @students.each do |student| %>
        <tr>
          <td><%= student.name %></td>
          <td><%= student.lesson_part ? student.lesson_part.display_number : 'No current lesson' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>